---
title: "Rasters and more"
output: html_document
---




## The basic rules for modern R code formatting 

*Note: Rules in <span style = "color: blue;">blue</span> can be carefully broken or have exceptions, while rules in black are firm!*

#### Assignment

* <span style = "color: blue;">Objects that are used in the creation of a parent object and not used again should not be assigned to the global environment.</span>

* Assigned names should be in all lowercase with multiple words should be separate by a `_`.

* Only use `=` when providing values to the formals of a function -- in all other instances use the `<-` assignment operator
    
* <span style = "color: blue;">All global assignment operators live on their own line [On the same line if generated by a non-named / primitive (non-R) function such as +, -, *, /, rep(), c(#, #, #...) w/ 3+ entries, and list(#, #...) w/ 2+ entries.]</span>

#### Code spacing

  * Maintain a minimum of one blank line between code blocks (chained or nested).
  
  * Maintain a minimum of one blank line between code blocks and comments ( or a short description to the right within functions) or section headers (Ctrl+Shift+R to create, accessible via table of contents button to top right).
  
  * All assignment and logical operators should be separated from other code by a leading and a trailing space
  
  * Commas should be separated from other code by a trailing space only

#### The magical maximum width, "76"

* <span style = "color: blue;">No line of code should exceed 76 characters in width (the magic number of tidy coding). Fix comments by Ctrl+Shift+/ and code by Ctrl+Shift+a. Addresses can be longer.</span>
    
#### Functions

* <span style = "color: blue;">Each formal of a function (i.e., argument) lives on its own line</span>

* <span style = "color: blue;">There should be no more than one call to a named function per line of code, except with list() and c().</span>

#### Other (Added by Me)

* Proper Indentation - Use Ctrl+Shift+I to fix improper Indentation

### Example

```{r}
# Making a silly data frame:

my_silly_data_frame <-
  data.frame(
    a = 1:4,
    b = 5:8,
    c = rep(
      c('hello', 'world'),
      each = 2),
    d = c('apple',
          'apricot',
          'avocado',
          'banana')
  )
```

